### PR TITLE
Allow disabling symbol resolution for some modules 

### PR DESCRIPTION
**Pull request by UnrealKaraulov**
https://github.com/VerySleepy/verysleepy/issues/109

### CODE REVIEW

**Comment by UnrealKaraulov** [comment]
@CyberShadow need Your help :)

**Comment by CyberShadow** [comment]
I can't test it but the diff looks good. Actually I would suggest to simplify it a little. The module list can just be a hidden option (and stored together with all options), for example as a string separated by `|`, then there's no need to do file I/O.

**Comment by CyberShadow** [comment]
> need Your help :)

What do you need help with, does it not work for you?

**Comment by UnrealKaraulov** [comment]
@CyberShadow Can it be merged, or do I need to make changes?

**Comment by CyberShadow** [comment]
I can merge this as is. But just so we understand each other...

1. Do you agree with the suggestion above (regardless of who implements it)? If not, maybe I misunderstood something?
2. Do you want to stop working on this and get it merged as is?

**Comment by UnrealKaraulov** [comment]
@CyberShadow as need for project owner:)

but I don't know how to add command line parser, it works for me as is, but you can improve it if needed

**Comment by CyberShadow** [comment]
I don't think we need a command line parser. My idea was to replace the file reading with `wxString::split`.

Also it would be nice to have a menu option (e.g. in the right-click menu) to toggle symbol resolution in the selected function's module, that would allow removing all other GUI for the option (so no changes in the options dialog window). Does that make sense to you?

**Comment by UnrealKaraulov** [comment]
> I don't think we need a command line parser. My idea was to replace the file reading with `wxString::split`.
> 
> Also it would be nice to have a menu option (e.g. in the right-click menu) to toggle symbol resolution in the selected function's module, that would allow removing all other GUI for the option (so no changes in the options dialog window). Does that make sense to you?

First I tried to add 'ignore module' to context menu, but it not works, I think because is not reloaded ? (I just don't know how to works code in this tool)

In this PR i just added read file beforce profile started. 

Yes I think it can be easy replaced to string::split without problems but I removed project from HDD ) You can do it without me...)

I'm leaving this PR!
I'm leaving this PR!

**Comment by CyberShadow** [comment]
OK, thanks! I will have a closer look at this when I'm home and have access to my Windows development VM.

**Comment by UnrealKaraulov** [comment]
@CyberShadow ........

**Comment by CyberShadow** [comment]
I forgor 💀

**Pull request closed without merging**
