### PR TITLE
Introduce a column that shows total CPU time in seconds since process start in process and threads list

### PR DESCRIPTION
**Pull request by quijote**

### CODE REVIEW

**Comment by CyberShadow** [comment]
I can't build Very Sleepy at the moment, but the diff looks good, so I'll merge this. Thanks!

**Comment by quijote** [comment]
Thank you for merging this so quickly back into master. 

I was only able to build with VS 2015 Community Edition and wxWidgets-3.1.0. I hope it still works for VS 2010 and wxWidgets-2.9.5. Would it make sense, to upgrade the project to require the newer IDE and library?

And what is the workflow for new releases for verysleepy? I still have some additional vague ideas for minor fixes or new features. What are the chances of getting a new official installer published within the next 4 weeks? Is there any documentation that shows how I could build an installer myself?

**Comment by CyberShadow** [comment]
> Would it make sense, to upgrade the project to require the newer IDE and library?

Backwards compatibility with older platforms would be something to consider. Newer VS versions regularly drop support for older Windows versions, both in terms of target platform, and as a requirement for installing the IDE itself.

> And what is the workflow for new releases for verysleepy? I still have some additional vague ideas for minor fixes or new features. What are the chances of getting a new official installer published within the next 4 weeks?

There hasn't been an official release in a while, which should probably be addressed. (On the other hand, I have not observed much demand for one, either.) The closest we've gotten to a release was ongoing work on MinGW symbol support (provided by the Dr. MinGW project), at that point users were reporting mixed results in getting it to work.

> Is there any documentation that shows how I could build an installer myself?

The InnoSetup script is included (see `installer.iss`).

**Comment by quijote** [comment]
Does the ongoing work on MinGW support prevent a release from master in the near future? Is this something that affects the stability of VerySleepy?

**Comment by CyberShadow** [comment]
> Does the ongoing work on MinGW support prevent a release from master in the near future?

The MinGW work happened a while ago, so it's not really ongoing any more. However, it hasn't exactly concluded either.

> Is this something that affects the stability of VerySleepy?

Potentially, when debugging MinGW programs.

**Pull request merged**
