### PR TITLE
Added command-line switch '/mt' and '/mbt'

### PR DESCRIPTION
**Pull request by RammerChoi**
'/mt' and '/mbt' are switches to select `AttachMode` when attaching a process by using an '/a' option.
'/mt' is an option to profile "main thread".
And '/mbt' is an option to profile "most busy thread".

This pull request is refactored from #47 on a new branch.
Thanks for your kind review.

### CODE REVIEW

**Comment by CyberShadow** [comment]
As mentioned in the first PR, could you please split out the refactoring changes into separate commits of their own?

**Comment by RammerChoi** [comment]
Sorry. I got it. 
Please wait a minute.

**Comment by CityOfStars** [comment]
I split out the refactoring changes into separate commits.
Please review again. Thanks.

**Comment by RammerChoi** [comment]
I split out the refactoring changes into separate commits.
Please review again. Thanks.

**Comment by CyberShadow** [comment]
Sorry for the delay. I'll look at this soon.

**Comment by CyberShadow** [comment]
Looks good, thanks!

**Pull request merged**
