### PR TITLE
+ hdpi fixes

### PR DESCRIPTION
**Pull request by djdron**
note : you need to upgrade wxwidgets to latest master to use HDPI features

### CODE REVIEW

**Comment by CyberShadow** [comment]
Hi and thank you for your contribution.

Unfortunately, as I don't use Windows (or Very Sleepy), I can only accept a contribution if it is complete and passes the CI. So, I need to ask you that any changes required to upgrade wxWidgets are added to this pull request before it can be merged.

Could you also please update the commit messages (here and in the other PRs) to be consistent with the format already used in this project?

**Comment by djdron** [comment]
Seems build is OK now, but tests failed ?

**Comment by CyberShadow** [comment]
"Build execution time has reached the maximum allowed time for your plan (60 minutes)."

It looks like it got stuck on execution. Possibly it is showing a pop-up or error message.

Perhaps the cause can be determined by connecting via RDP: 
https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

**Comment by djdron** [comment]
I need to setup appveyor to my fork ?

**Comment by CyberShadow** [comment]
I'm not 100% sure if it will work, but you could try to temporarily edit `appveyor.yml` in this pull request.

**Comment by djdron** [comment]
image
It got stuck on this in some tests. I killed Sleepy process and tests continue.

**Comment by djdron** [comment]
reproduced this on local machine, trying to fix

**Comment by djdron** [comment]
Seems to work ok now)
What did you mean to do with commit messages? remove "+" sign ?

**Comment by CyberShadow** [comment]
Thank you very much! This is fantastic work.

>  What did you mean to do with commit messages? remove "+" sign ?

Up to you if you want to do this and otherwise clean up history; alternatively I can squash everything into a single commit.

If you want to clean up history, what I would do is:

- Commit messages:
   - Remove the + sign as you mentioned (does it mean something? It's not a convention I've seen anywhere else)
   - If the change pertains to a single file or component, put its name at the frotn (e.g. "mythread: Commit message here")
   - Uppercase the first letter
   - Reword the subject so that it follows the rule that "If applied, this commit will **_your subject line here_**"

  See e.g. https://chris.beams.io/posts/git-commit/ for details.
- Commit order:
   - Remove commits that have been reverted
   - Squash together commits that, together, form a single logical and self-contained change
   - Reorder commits so that ideally the test suite continues passing after every commit (meaning, early commits may introduce changes that are only used/activated by later commits)

Up to you if this is something that you want to do.

**Comment by djdron** [comment]
> Thank you very much! This is fantastic work.

You're welcome) Thanks for this beautiful profiler.

> Up to you if you want to do this and otherwise clean up history; alternatively I can squash everything into a single commit.

Please do it, because i don't know how to re-arrange & combine pushed commits.
Do i need to create new branch from master, cherry-pick them, combine if necessary and create new PR ?
Or i need to push --force ?

>   See e.g. https://chris.beams.io/posts/git-commit/ for details.

Thanks for info.

> Up to you if this is something that you want to do.

I don't really want

**Pull request merged**
